name: coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - run: pip install nox==2020.8.22
    - run: pip install poetry==1.1.3
    - run: nox --pythons 3.8 --sessions test coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
